[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Nejnovější stabilní verze eframe
eframe = { version = "0.27.0", default-features = false, features = ["glow", "android-native-activity"] }
# Odpovídající verze aktivity
android-activity = { version = "0.5", features = ["native-activity"] }
# Logování pro případ nouze
android_logger = "0.13"
log = "0.4"

[package.metadata.android]
package = "com.moje.cnckalkulacka"
label = "CNC Test"
android_version = 33
target_sdk_version = 33
min_sdk_version = 26
fullscreen = true
build_targets = ["aarch64-linux-android"]
