[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Použijeme stabilní verzi eframe
eframe = { version = "0.22", default-features = false, features = ["glow", "android-native-activity"] }
# Tato verze musí být sjednocena
android-activity = { version = "0.4.3", features = ["native-activity"] }

[patch.crates-io]
# Tímto vynutíme jednu verzi pro celý projekt a předejdeme pádu
android-activity = { version = "0.4.3", features = ["native-activity"] }

[package.metadata.android]
package = "com.moje.cnckalkulacka"
label = "CNC Kalkulačka"
android_version = 30
target_sdk_version = 31
min_sdk_version = 21

