[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# ZDE JE TA MAGICKÁ OPRAVA: Zapneme Android feature přímo tady
eframe = { version = "0.24.0", features = ["android-native-activity"] }
serde = { version = "1", features = ["derive"] }

[package.metadata.android]
package = "com.moje.cnckalkulacka"
label = "CNC Kalkulačka"
android_version = 33
target_sdk_version = 33
min_sdk_version = 26
fullscreen = true

