[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Grafika
eframe = { version = "0.22.0", default-features = false, features = ["glow", "android-native-activity"] }
# Logger jsme VYHODILI, aby nedělal problémy
# Android aktivita - fixnutá verze
android-activity = { version = "=0.4.3", features = ["native-activity"] }

[package.metadata.android]
package = "com.moje.cnckalkulacka"
label = "CNC Kalkulačka"
# TADY JE TA ZMĚNA - MUSÍ TAM BÝT 33 (GitHub má 33, nemá 30)
android_version = 33
target_sdk_version = 33
min_sdk_version = 23
fullscreen = true
# Podpora pro staré i nové mobily
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
