[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

# TOTO JE TA KLÍČOVÁ ZMĚNA:
# Natvrdo pojmenujeme knihovnu "main_lib", aby nebyly zmatky s pomlčkami
[lib]
name = "main_lib"
crate-type = ["cdylib"]

[dependencies]
# Stabilní verze eframe a activity
eframe = { version = "0.27.2", default-features = false, features = ["glow", "android-native-activity"] }
android-activity = { version = "0.5.2", features = ["native-activity"] }
log = "0.4"
android_logger = "0.13"

[package.metadata.android]
package = "com.cnc.simple" 
label = "CNC Final"
android_version = 33
target_sdk_version = 33
min_sdk_version = 21
fullscreen = true
# Řekneme Androidu: "Hledej přesně tuto knihovnu"
lib_name = "main_lib"
permissions = ["android.permission.INTERNET"]

# Stavíme pro obě architektury (proti pádům na 32bit mobilech)
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
