[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Vypneme default features, aby se tam necpal "wgpu" (Vulkan)
# Zapneme JEN "glow" (OpenGL) a podporu pro Android
eframe = { version = "0.27.2", default-features = false, features = ["glow", "android-native-activity", "wayland", "x11"] }

# Závislost pro logování
log = "0.4"
android_logger = "0.13"

# Lepidlo pro Android
android-activity = { version = "0.5.2", features = ["native-activity"] }

[package.metadata.android]
package = "com.moje.cnckalkulacka"
label = "CNC Fix"
android_version = 33
target_sdk_version = 33
min_sdk_version = 21
fullscreen = true
# Povolení internetu (některé telefony bez toho padají)
permissions = ["android.permission.INTERNET"]

# Stavíme pro obě architektury
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
