[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# ZMĚNA: Vypneme defaultní WGPU a zapneme bezpečný GLOW (OpenGL)
eframe = { version = "0.24.0", default-features = false, features = ["default_fonts", "glow", "android-native-activity"] }
serde = { version = "1", features = ["derive"] }
android-activity = { version = "0.4", features = ["native-activity"] }

# Přidáme logování, kdyby to stále zlobilo
android_logger = "0.13"
log = "0.4"

[package.metadata.android]
package = "com.moje.cnckalkulacka"
label = "CNC Kalkulačka"
android_version = 33
target_sdk_version = 33
min_sdk_version = 26
fullscreen = true

