[package]
name = "cnc_kalkulacka"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
eframe = { version = "0.22.0", default-features = false, features = ["glow", "android-native-activity"] }
android-activity = { version = "=0.4.3", features = ["native-activity"] }
log = "0.4"
android_logger = "0.13"

[package.metadata.android]
package = "com.moje.cnckalkulacka"
label = "CNC KalkulaÄka"
android_version = 33
target_sdk_version = 33
min_sdk_version = 24
fullscreen = true
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
