name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi

      # Instalace nástroje xbuild (náhrada za cargo-apk)
      - name: Install xbuild
        run: cargo install xbuild

      # Build pomocí xbuild (automaticky najde správné SDK)
      - name: Build APK with xbuild
        run: |
            xbuild apk --target aarch64-linux-android --target armv7-linux-androideabi

      - uses: actions/upload-artifact@v4
        with:
          name: cnc-kalkulacka
          path: target/android-artifacts/app.apk
