name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi
      - run: cargo install cargo-apk
      - name: Build APK (Universal)
        run: cargo apk build
      - uses: actions/upload-artifact@v4
        with:
          name: cnc-kalkulacka
          path: target/debug/apk/cnc_kalkulacka.apk
